### ISSUE TITLE
Encoded files become corrupted.

### ISSUE THREAD

**Issue by LiquidAppleJuice** [damianb/SBAsset6#4]
Trying to grab an encoded file (.png/.ogg/etc) returns a copy with a significant portion of the characters swapped with unicode replacement characters. Examples below.
**'atlas.ogg' - Original**
https://cdn.discordapp.com/attachments/176662557199695883/356608939279908864/atlas.ogg
**'atlas2.ogg' - Copy**
https://cdn.discordapp.com/attachments/176662557199695883/356608965544771589/atlas2.ogg

**Comment by damianb** [comment]
Smells like it might be something to do with this:

```
return (await sbuf.read(filelength)).toString()
```

...in which case, I need to identify when to convert to utf8 string, and when *not* to.  Hmm. Tricky.

**Comment by LiquidAppleJuice** [comment]
Grabbed this snippet from stackoverflow; should check for changes during the conversion.

>  function isValidUTF8(buf){
>    return Buffer.compare(new Buffer(buf.toString(),'utf8') , buf) === 0;
>   }

**Comment by damianb** [comment]
Looks like there's no way around it - in order to preserve original encoding, I *cannot* toString() at all...

Going to need to make a breaking change.  Adding regression tests.
